// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kind.proto

#ifndef PROTOBUF_kind_2eproto__INCLUDED
#define PROTOBUF_kind_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_kind_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsrole_upgrade_cfgImpl();
void InitDefaultsrole_upgrade_cfg();
inline void InitDefaults() {
  InitDefaultsrole_upgrade_cfg();
}
}  // namespace protobuf_kind_2eproto
class role_upgrade_cfg;
class role_upgrade_cfgDefaultTypeInternal;
extern role_upgrade_cfgDefaultTypeInternal _role_upgrade_cfg_default_instance_;

// ===================================================================

class role_upgrade_cfg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:role_upgrade_cfg) */ {
 public:
  role_upgrade_cfg();
  virtual ~role_upgrade_cfg();

  role_upgrade_cfg(const role_upgrade_cfg& from);

  inline role_upgrade_cfg& operator=(const role_upgrade_cfg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  role_upgrade_cfg(role_upgrade_cfg&& from) noexcept
    : role_upgrade_cfg() {
    *this = ::std::move(from);
  }

  inline role_upgrade_cfg& operator=(role_upgrade_cfg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const role_upgrade_cfg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const role_upgrade_cfg* internal_default_instance() {
    return reinterpret_cast<const role_upgrade_cfg*>(
               &_role_upgrade_cfg_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(role_upgrade_cfg* other);
  friend void swap(role_upgrade_cfg& a, role_upgrade_cfg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline role_upgrade_cfg* New() const PROTOBUF_FINAL { return New(NULL); }

  role_upgrade_cfg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const role_upgrade_cfg& from);
  void MergeFrom(const role_upgrade_cfg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(role_upgrade_cfg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 Id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // uint32 Level = 2;
  void clear_level();
  static const int kLevelFieldNumber = 2;
  ::google::protobuf::uint32 level() const;
  void set_level(::google::protobuf::uint32 value);

  // uint32 CostType = 3;
  void clear_costtype();
  static const int kCostTypeFieldNumber = 3;
  ::google::protobuf::uint32 costtype() const;
  void set_costtype(::google::protobuf::uint32 value);

  // int32 CostValue = 4;
  void clear_costvalue();
  static const int kCostValueFieldNumber = 4;
  ::google::protobuf::int32 costvalue() const;
  void set_costvalue(::google::protobuf::int32 value);

  // int32 ScoreAdd = 5;
  void clear_scoreadd();
  static const int kScoreAddFieldNumber = 5;
  ::google::protobuf::int32 scoreadd() const;
  void set_scoreadd(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:role_upgrade_cfg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 level_;
  ::google::protobuf::uint32 costtype_;
  ::google::protobuf::int32 costvalue_;
  ::google::protobuf::int32 scoreadd_;
  mutable int _cached_size_;
  friend struct ::protobuf_kind_2eproto::TableStruct;
  friend void ::protobuf_kind_2eproto::InitDefaultsrole_upgrade_cfgImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// role_upgrade_cfg

// uint32 Id = 1;
inline void role_upgrade_cfg::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 role_upgrade_cfg::id() const {
  // @@protoc_insertion_point(field_get:role_upgrade_cfg.Id)
  return id_;
}
inline void role_upgrade_cfg::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:role_upgrade_cfg.Id)
}

// uint32 Level = 2;
inline void role_upgrade_cfg::clear_level() {
  level_ = 0u;
}
inline ::google::protobuf::uint32 role_upgrade_cfg::level() const {
  // @@protoc_insertion_point(field_get:role_upgrade_cfg.Level)
  return level_;
}
inline void role_upgrade_cfg::set_level(::google::protobuf::uint32 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:role_upgrade_cfg.Level)
}

// uint32 CostType = 3;
inline void role_upgrade_cfg::clear_costtype() {
  costtype_ = 0u;
}
inline ::google::protobuf::uint32 role_upgrade_cfg::costtype() const {
  // @@protoc_insertion_point(field_get:role_upgrade_cfg.CostType)
  return costtype_;
}
inline void role_upgrade_cfg::set_costtype(::google::protobuf::uint32 value) {
  
  costtype_ = value;
  // @@protoc_insertion_point(field_set:role_upgrade_cfg.CostType)
}

// int32 CostValue = 4;
inline void role_upgrade_cfg::clear_costvalue() {
  costvalue_ = 0;
}
inline ::google::protobuf::int32 role_upgrade_cfg::costvalue() const {
  // @@protoc_insertion_point(field_get:role_upgrade_cfg.CostValue)
  return costvalue_;
}
inline void role_upgrade_cfg::set_costvalue(::google::protobuf::int32 value) {
  
  costvalue_ = value;
  // @@protoc_insertion_point(field_set:role_upgrade_cfg.CostValue)
}

// int32 ScoreAdd = 5;
inline void role_upgrade_cfg::clear_scoreadd() {
  scoreadd_ = 0;
}
inline ::google::protobuf::int32 role_upgrade_cfg::scoreadd() const {
  // @@protoc_insertion_point(field_get:role_upgrade_cfg.ScoreAdd)
  return scoreadd_;
}
inline void role_upgrade_cfg::set_scoreadd(::google::protobuf::int32 value) {
  
  scoreadd_ = value;
  // @@protoc_insertion_point(field_set:role_upgrade_cfg.ScoreAdd)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_kind_2eproto__INCLUDED
