// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_header_v3.proto

#ifndef PROTOBUF_pb_5fheader_5fv3_2eproto__INCLUDED
#define PROTOBUF_pb_5fheader_5fv3_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_pb_5fheader_5fv3_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsxresloader_headerImpl();
void InitDefaultsxresloader_header();
void InitDefaultsxresloader_datablocksImpl();
void InitDefaultsxresloader_datablocks();
inline void InitDefaults() {
  InitDefaultsxresloader_header();
  InitDefaultsxresloader_datablocks();
}
}  // namespace protobuf_pb_5fheader_5fv3_2eproto
namespace com {
namespace owent {
namespace xresloader {
namespace pb {
class xresloader_datablocks;
class xresloader_datablocksDefaultTypeInternal;
extern xresloader_datablocksDefaultTypeInternal _xresloader_datablocks_default_instance_;
class xresloader_header;
class xresloader_headerDefaultTypeInternal;
extern xresloader_headerDefaultTypeInternal _xresloader_header_default_instance_;
}  // namespace pb
}  // namespace xresloader
}  // namespace owent
}  // namespace com
namespace com {
namespace owent {
namespace xresloader {
namespace pb {

// ===================================================================

class xresloader_header : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.owent.xresloader.pb.xresloader_header) */ {
 public:
  xresloader_header();
  virtual ~xresloader_header();

  xresloader_header(const xresloader_header& from);

  inline xresloader_header& operator=(const xresloader_header& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  xresloader_header(xresloader_header&& from) noexcept
    : xresloader_header() {
    *this = ::std::move(from);
  }

  inline xresloader_header& operator=(xresloader_header&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const xresloader_header& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const xresloader_header* internal_default_instance() {
    return reinterpret_cast<const xresloader_header*>(
               &_xresloader_header_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(xresloader_header* other);
  friend void swap(xresloader_header& a, xresloader_header& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline xresloader_header* New() const PROTOBUF_FINAL { return New(NULL); }

  xresloader_header* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const xresloader_header& from);
  void MergeFrom(const xresloader_header& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(xresloader_header* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string xres_ver = 1;
  void clear_xres_ver();
  static const int kXresVerFieldNumber = 1;
  const ::std::string& xres_ver() const;
  void set_xres_ver(const ::std::string& value);
  #if LANG_CXX11
  void set_xres_ver(::std::string&& value);
  #endif
  void set_xres_ver(const char* value);
  void set_xres_ver(const char* value, size_t size);
  ::std::string* mutable_xres_ver();
  ::std::string* release_xres_ver();
  void set_allocated_xres_ver(::std::string* xres_ver);

  // string data_ver = 2;
  void clear_data_ver();
  static const int kDataVerFieldNumber = 2;
  const ::std::string& data_ver() const;
  void set_data_ver(const ::std::string& value);
  #if LANG_CXX11
  void set_data_ver(::std::string&& value);
  #endif
  void set_data_ver(const char* value);
  void set_data_ver(const char* value, size_t size);
  ::std::string* mutable_data_ver();
  ::std::string* release_data_ver();
  void set_allocated_data_ver(::std::string* data_ver);

  // string hash_code = 4;
  void clear_hash_code();
  static const int kHashCodeFieldNumber = 4;
  const ::std::string& hash_code() const;
  void set_hash_code(const ::std::string& value);
  #if LANG_CXX11
  void set_hash_code(::std::string&& value);
  #endif
  void set_hash_code(const char* value);
  void set_hash_code(const char* value, size_t size);
  ::std::string* mutable_hash_code();
  ::std::string* release_hash_code();
  void set_allocated_hash_code(::std::string* hash_code);

  // uint32 count = 3;
  void clear_count();
  static const int kCountFieldNumber = 3;
  ::google::protobuf::uint32 count() const;
  void set_count(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:com.owent.xresloader.pb.xresloader_header)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr xres_ver_;
  ::google::protobuf::internal::ArenaStringPtr data_ver_;
  ::google::protobuf::internal::ArenaStringPtr hash_code_;
  ::google::protobuf::uint32 count_;
  mutable int _cached_size_;
  friend struct ::protobuf_pb_5fheader_5fv3_2eproto::TableStruct;
  friend void ::protobuf_pb_5fheader_5fv3_2eproto::InitDefaultsxresloader_headerImpl();
};
// -------------------------------------------------------------------

class xresloader_datablocks : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.owent.xresloader.pb.xresloader_datablocks) */ {
 public:
  xresloader_datablocks();
  virtual ~xresloader_datablocks();

  xresloader_datablocks(const xresloader_datablocks& from);

  inline xresloader_datablocks& operator=(const xresloader_datablocks& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  xresloader_datablocks(xresloader_datablocks&& from) noexcept
    : xresloader_datablocks() {
    *this = ::std::move(from);
  }

  inline xresloader_datablocks& operator=(xresloader_datablocks&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const xresloader_datablocks& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const xresloader_datablocks* internal_default_instance() {
    return reinterpret_cast<const xresloader_datablocks*>(
               &_xresloader_datablocks_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(xresloader_datablocks* other);
  friend void swap(xresloader_datablocks& a, xresloader_datablocks& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline xresloader_datablocks* New() const PROTOBUF_FINAL { return New(NULL); }

  xresloader_datablocks* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const xresloader_datablocks& from);
  void MergeFrom(const xresloader_datablocks& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(xresloader_datablocks* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated bytes data_block = 2;
  int data_block_size() const;
  void clear_data_block();
  static const int kDataBlockFieldNumber = 2;
  const ::std::string& data_block(int index) const;
  ::std::string* mutable_data_block(int index);
  void set_data_block(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_data_block(int index, ::std::string&& value);
  #endif
  void set_data_block(int index, const char* value);
  void set_data_block(int index, const void* value, size_t size);
  ::std::string* add_data_block();
  void add_data_block(const ::std::string& value);
  #if LANG_CXX11
  void add_data_block(::std::string&& value);
  #endif
  void add_data_block(const char* value);
  void add_data_block(const void* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& data_block() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_data_block();

  // .com.owent.xresloader.pb.xresloader_header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::com::owent::xresloader::pb::xresloader_header& header() const;
  ::com::owent::xresloader::pb::xresloader_header* release_header();
  ::com::owent::xresloader::pb::xresloader_header* mutable_header();
  void set_allocated_header(::com::owent::xresloader::pb::xresloader_header* header);

  // @@protoc_insertion_point(class_scope:com.owent.xresloader.pb.xresloader_datablocks)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> data_block_;
  ::com::owent::xresloader::pb::xresloader_header* header_;
  mutable int _cached_size_;
  friend struct ::protobuf_pb_5fheader_5fv3_2eproto::TableStruct;
  friend void ::protobuf_pb_5fheader_5fv3_2eproto::InitDefaultsxresloader_datablocksImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// xresloader_header

// string xres_ver = 1;
inline void xresloader_header::clear_xres_ver() {
  xres_ver_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& xresloader_header::xres_ver() const {
  // @@protoc_insertion_point(field_get:com.owent.xresloader.pb.xresloader_header.xres_ver)
  return xres_ver_.GetNoArena();
}
inline void xresloader_header::set_xres_ver(const ::std::string& value) {
  
  xres_ver_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.owent.xresloader.pb.xresloader_header.xres_ver)
}
#if LANG_CXX11
inline void xresloader_header::set_xres_ver(::std::string&& value) {
  
  xres_ver_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.owent.xresloader.pb.xresloader_header.xres_ver)
}
#endif
inline void xresloader_header::set_xres_ver(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  xres_ver_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.owent.xresloader.pb.xresloader_header.xres_ver)
}
inline void xresloader_header::set_xres_ver(const char* value, size_t size) {
  
  xres_ver_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.owent.xresloader.pb.xresloader_header.xres_ver)
}
inline ::std::string* xresloader_header::mutable_xres_ver() {
  
  // @@protoc_insertion_point(field_mutable:com.owent.xresloader.pb.xresloader_header.xres_ver)
  return xres_ver_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* xresloader_header::release_xres_ver() {
  // @@protoc_insertion_point(field_release:com.owent.xresloader.pb.xresloader_header.xres_ver)
  
  return xres_ver_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void xresloader_header::set_allocated_xres_ver(::std::string* xres_ver) {
  if (xres_ver != NULL) {
    
  } else {
    
  }
  xres_ver_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), xres_ver);
  // @@protoc_insertion_point(field_set_allocated:com.owent.xresloader.pb.xresloader_header.xres_ver)
}

// string data_ver = 2;
inline void xresloader_header::clear_data_ver() {
  data_ver_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& xresloader_header::data_ver() const {
  // @@protoc_insertion_point(field_get:com.owent.xresloader.pb.xresloader_header.data_ver)
  return data_ver_.GetNoArena();
}
inline void xresloader_header::set_data_ver(const ::std::string& value) {
  
  data_ver_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.owent.xresloader.pb.xresloader_header.data_ver)
}
#if LANG_CXX11
inline void xresloader_header::set_data_ver(::std::string&& value) {
  
  data_ver_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.owent.xresloader.pb.xresloader_header.data_ver)
}
#endif
inline void xresloader_header::set_data_ver(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_ver_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.owent.xresloader.pb.xresloader_header.data_ver)
}
inline void xresloader_header::set_data_ver(const char* value, size_t size) {
  
  data_ver_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.owent.xresloader.pb.xresloader_header.data_ver)
}
inline ::std::string* xresloader_header::mutable_data_ver() {
  
  // @@protoc_insertion_point(field_mutable:com.owent.xresloader.pb.xresloader_header.data_ver)
  return data_ver_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* xresloader_header::release_data_ver() {
  // @@protoc_insertion_point(field_release:com.owent.xresloader.pb.xresloader_header.data_ver)
  
  return data_ver_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void xresloader_header::set_allocated_data_ver(::std::string* data_ver) {
  if (data_ver != NULL) {
    
  } else {
    
  }
  data_ver_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data_ver);
  // @@protoc_insertion_point(field_set_allocated:com.owent.xresloader.pb.xresloader_header.data_ver)
}

// uint32 count = 3;
inline void xresloader_header::clear_count() {
  count_ = 0u;
}
inline ::google::protobuf::uint32 xresloader_header::count() const {
  // @@protoc_insertion_point(field_get:com.owent.xresloader.pb.xresloader_header.count)
  return count_;
}
inline void xresloader_header::set_count(::google::protobuf::uint32 value) {
  
  count_ = value;
  // @@protoc_insertion_point(field_set:com.owent.xresloader.pb.xresloader_header.count)
}

// string hash_code = 4;
inline void xresloader_header::clear_hash_code() {
  hash_code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& xresloader_header::hash_code() const {
  // @@protoc_insertion_point(field_get:com.owent.xresloader.pb.xresloader_header.hash_code)
  return hash_code_.GetNoArena();
}
inline void xresloader_header::set_hash_code(const ::std::string& value) {
  
  hash_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.owent.xresloader.pb.xresloader_header.hash_code)
}
#if LANG_CXX11
inline void xresloader_header::set_hash_code(::std::string&& value) {
  
  hash_code_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.owent.xresloader.pb.xresloader_header.hash_code)
}
#endif
inline void xresloader_header::set_hash_code(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  hash_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.owent.xresloader.pb.xresloader_header.hash_code)
}
inline void xresloader_header::set_hash_code(const char* value, size_t size) {
  
  hash_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.owent.xresloader.pb.xresloader_header.hash_code)
}
inline ::std::string* xresloader_header::mutable_hash_code() {
  
  // @@protoc_insertion_point(field_mutable:com.owent.xresloader.pb.xresloader_header.hash_code)
  return hash_code_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* xresloader_header::release_hash_code() {
  // @@protoc_insertion_point(field_release:com.owent.xresloader.pb.xresloader_header.hash_code)
  
  return hash_code_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void xresloader_header::set_allocated_hash_code(::std::string* hash_code) {
  if (hash_code != NULL) {
    
  } else {
    
  }
  hash_code_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hash_code);
  // @@protoc_insertion_point(field_set_allocated:com.owent.xresloader.pb.xresloader_header.hash_code)
}

// -------------------------------------------------------------------

// xresloader_datablocks

// .com.owent.xresloader.pb.xresloader_header header = 1;
inline bool xresloader_datablocks::has_header() const {
  return this != internal_default_instance() && header_ != NULL;
}
inline void xresloader_datablocks::clear_header() {
  if (GetArenaNoVirtual() == NULL && header_ != NULL) {
    delete header_;
  }
  header_ = NULL;
}
inline const ::com::owent::xresloader::pb::xresloader_header& xresloader_datablocks::header() const {
  const ::com::owent::xresloader::pb::xresloader_header* p = header_;
  // @@protoc_insertion_point(field_get:com.owent.xresloader.pb.xresloader_datablocks.header)
  return p != NULL ? *p : *reinterpret_cast<const ::com::owent::xresloader::pb::xresloader_header*>(
      &::com::owent::xresloader::pb::_xresloader_header_default_instance_);
}
inline ::com::owent::xresloader::pb::xresloader_header* xresloader_datablocks::release_header() {
  // @@protoc_insertion_point(field_release:com.owent.xresloader.pb.xresloader_datablocks.header)
  
  ::com::owent::xresloader::pb::xresloader_header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::com::owent::xresloader::pb::xresloader_header* xresloader_datablocks::mutable_header() {
  
  if (header_ == NULL) {
    header_ = new ::com::owent::xresloader::pb::xresloader_header;
  }
  // @@protoc_insertion_point(field_mutable:com.owent.xresloader.pb.xresloader_datablocks.header)
  return header_;
}
inline void xresloader_datablocks::set_allocated_header(::com::owent::xresloader::pb::xresloader_header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete header_;
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:com.owent.xresloader.pb.xresloader_datablocks.header)
}

// repeated bytes data_block = 2;
inline int xresloader_datablocks::data_block_size() const {
  return data_block_.size();
}
inline void xresloader_datablocks::clear_data_block() {
  data_block_.Clear();
}
inline const ::std::string& xresloader_datablocks::data_block(int index) const {
  // @@protoc_insertion_point(field_get:com.owent.xresloader.pb.xresloader_datablocks.data_block)
  return data_block_.Get(index);
}
inline ::std::string* xresloader_datablocks::mutable_data_block(int index) {
  // @@protoc_insertion_point(field_mutable:com.owent.xresloader.pb.xresloader_datablocks.data_block)
  return data_block_.Mutable(index);
}
inline void xresloader_datablocks::set_data_block(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:com.owent.xresloader.pb.xresloader_datablocks.data_block)
  data_block_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void xresloader_datablocks::set_data_block(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:com.owent.xresloader.pb.xresloader_datablocks.data_block)
  data_block_.Mutable(index)->assign(std::move(value));
}
#endif
inline void xresloader_datablocks::set_data_block(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  data_block_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:com.owent.xresloader.pb.xresloader_datablocks.data_block)
}
inline void xresloader_datablocks::set_data_block(int index, const void* value, size_t size) {
  data_block_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.owent.xresloader.pb.xresloader_datablocks.data_block)
}
inline ::std::string* xresloader_datablocks::add_data_block() {
  // @@protoc_insertion_point(field_add_mutable:com.owent.xresloader.pb.xresloader_datablocks.data_block)
  return data_block_.Add();
}
inline void xresloader_datablocks::add_data_block(const ::std::string& value) {
  data_block_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:com.owent.xresloader.pb.xresloader_datablocks.data_block)
}
#if LANG_CXX11
inline void xresloader_datablocks::add_data_block(::std::string&& value) {
  data_block_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:com.owent.xresloader.pb.xresloader_datablocks.data_block)
}
#endif
inline void xresloader_datablocks::add_data_block(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  data_block_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:com.owent.xresloader.pb.xresloader_datablocks.data_block)
}
inline void xresloader_datablocks::add_data_block(const void* value, size_t size) {
  data_block_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:com.owent.xresloader.pb.xresloader_datablocks.data_block)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
xresloader_datablocks::data_block() const {
  // @@protoc_insertion_point(field_list:com.owent.xresloader.pb.xresloader_datablocks.data_block)
  return data_block_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
xresloader_datablocks::mutable_data_block() {
  // @@protoc_insertion_point(field_mutable_list:com.owent.xresloader.pb.xresloader_datablocks.data_block)
  return &data_block_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace xresloader
}  // namespace owent
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pb_5fheader_5fv3_2eproto__INCLUDED
