name: "main"

on: # @see https://help.github.com/en/articles/events-that-trigger-workflows#webhook-events
  push:
    branches: # Array of patterns that match refs/heads
      - main

jobs:
  document: # job id, can be any string
    name: Document
    # This job runs on Linux
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x64-linux
            cc: gcc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build & Test
        shell: bash
        run: |
          python3 -m pip install --user --upgrade pip;
          python3 -m pip install --user --upgrade -r requirements.txt;
          sphinx-build -b html -a source output;
          echo "xresloader.atframe.work" > output/CNAME ;
          echo "" > output/.nojekyll
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        env:
          COMMIT_REF: ${{ github.ref }}
          DOCUMENT_DEPLOY_KEY: ${{ secrets.DOCUMENT_DEPLOY_KEY }}
          DOCUMENT_DEPLOY_KEY_GITEE: ${{ secrets.DOCUMENT_DEPLOY_KEY_GITEE }}
        shell: bash
        run: |
          cd output ;
          git config --global init.defaultBranch main ;
          git init ;
          git add . .nojekyll ;
          mkdir -p $HOME/.ssh ;
          chmod 700 $HOME/.ssh ;
          echo "$DOCUMENT_DEPLOY_KEY" > $HOME/.ssh/deploy.key ;
          echo "$DOCUMENT_DEPLOY_KEY_GITEE" > $HOME/.ssh/deploy-gitee.key ;
          chmod 600 $HOME/.ssh/deploy.key $HOME/.ssh/deploy-gitee.key ;
          export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentityFile=$HOME/.ssh/deploy.key" ;
          git -c user.name='owent' -c user.email='admin@owent.net' commit -m "Delpoy document for $COMMIT_REF";
          git push -f -q git@github.com:xresloader/xresloader-docs-website.git HEAD:main ;
          export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentityFile=$HOME/.ssh/deploy-gitee.key" ;
          git push -f -q git@gitee.com:xresloader/xresloader-docs-website.git HEAD:main ;
